version: "3.9"

services:
  web:
    build:
      context: .
      args:
        VITE_GA_MEASUREMENT_ID: ${VITE_GA_MEASUREMENT_ID}
        VITE_SHOW_DEVTOOLS: ${VITE_SHOW_DEVTOOLS}
    image: veo3-app:latest
    container_name: veo3-web
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    # Production service (default)

  dev:
    image: node:20-alpine
    working_dir: /app
    container_name: veo3-dev
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    volumes:
      - ./:/app
      - /app/node_modules
    profiles: ["dev"]
